services:
  - type: web
    name: mother-fitness-backend
    runtime: node
    repo: https://github.com/motherfitnessandrahalli-commits/mother-fitness-backend
    region: singapore
    plan: free
    branch: main
    rootDir: ./
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 24h
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: EMAIL_FROM
        value: Mother Fitness <motherfitnessandrahalli@gmail.com>
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 465
      - key: EMAIL_USER
        value: motherfitnessandrahalli@gmail.com
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://mother-fitness-backend-v2.onrender.com
      - key: SOCKET_CORS_ORIGIN
        value: https://mother-fitness-backend-v2.onrender.com
